const router = require('express').Router();
const c = require('../../controllers/erpControllers/leadController');
const { requireAdmin } = require('../../middlewares/roleAccess');
router.get('/dashboard', c.dashboard);
router.post('/assign', requireAdmin, c.assign);
router.post('/', c.create);
router.get('/', c.list);
router.get('/:id', c.read);
router.put('/:id', c.update);
router.delete('/:id', requireAdmin, c.delete);
module.exports = router;
